# Generated by Django 3.2 on 2021-12-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_menu_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='submenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
