# Generated by Django 3.2 on 2022-01-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_news_newsi18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsi18n',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contents.news'),
            preserve_default=False,
        ),
    ]
