# Generated by Django 3.2 on 2022-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_newsi18n_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsi18n',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsi18n',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='newsi18n',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'),
                                            ('tr', 'Turkish'), ('kg', 'Kyrgyz')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
