# Generated by Django 3.2 on 2022-01-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='longitude',
        ),
        migrations.AddField(
            model_name='institution',
            name='accommodation',
            field=models.TextField(default='', verbose_name='Accommodation details'),
        ),
        migrations.AddField(
            model_name='institution',
            name='scholarship',
            field=models.TextField(default='', verbose_name='Scholarship details'),
        ),
        migrations.AddField(
            model_name='institutioni18n',
            name='accommodation',
            field=models.TextField(default='', verbose_name='Accommodation details'),
        ),
        migrations.AddField(
            model_name='institutioni18n',
            name='scholarship',
            field=models.TextField(default='', verbose_name='Scholarship details'),
        ),
    ]
