# Generated by Django 3.2.5 on 2021-09-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Agent'), ('S', 'Student')], default='S', max_length=1),
        ),
    ]
