# Generated by Django 3.2 on 2021-12-15 11:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submenus', to='contents.menu')),
            ],
            options={
                'db_table': 'submenu',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('submenu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='contents.submenu')),
            ],
            options={
                'verbose_name': 'post',
                'db_table': 'text_block',
            },
        ),
        migrations.CreateModel(
            name='TextBlockMenuI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Translation')),
                ('text_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='contents.textblock', verbose_name='Original name')),
            ],
            options={
                'verbose_name': 'post translation',
                'db_table': 'text_block_i18n',
            },
        ),
        migrations.CreateModel(
            name='SubMenuI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2)),
                ('title', models.CharField(max_length=256, verbose_name='Translation')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='contents.submenu', verbose_name='Original name')),
            ],
            options={
                'verbose_name': 'submenu translation',
                'db_table': 'submenu_i18n',
            },
        ),
        migrations.CreateModel(
            name='MenuI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2)),
                ('title', models.CharField(max_length=256, verbose_name='Translation')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='contents.menu', verbose_name='Original name')),
            ],
            options={
                'verbose_name': 'menu translation',
                'db_table': 'menu_i18n',
            },
        ),
    ]
