# Generated by Django 3.2 on 2021-12-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textblockmenui18n',
            name='submenu',
        ),
        migrations.AddField(
            model_name='textblock',
            name='submenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.submenu'),
        ),
    ]
