version: '3.7'

services:
  api:
    build: .
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/api
    depends_on:
      - db
  db:
    image: 'postgres:13'
    env_file:
      - .env.dev
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

volumes:
  db-data: