version: "3.3"

services:
  db:
    container_name: eduwise-db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: eduwise-api
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/api/staticfiles
      - media_volume:/api/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/api/staticfiles
      - media_volume:/api/mediafiles
    ports:
      - "80:80"
    depends_on:
      - api
volumes:
  postgres_data:
  static_volume:
  media_volume: