# Generated by Django 3.2 on 2022-01-07 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields

from eduwise.utils.data.countries import COUNTRIES


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=COUNTRIES)),
                ('iso_code', models.CharField(editable=False, max_length=3, unique=True,
                                              validators=[django.core.validators.RegexValidator(code='no match',
                                                                                                message='ISO code has '
                                                                                                        'to be of '
                                                                                                        'length 3',
                                                                                                regex='^.{3}$')])),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces',
                                              to='locations.country')),
            ],
            options={
                'db_table': 'province',
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities',
                                              to='locations.country')),
                ('province', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='country',
                                                                       chained_model_field='country', null=True,
                                                                       on_delete=django.db.models.deletion.CASCADE,
                                                                       to='locations.province')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'city',
                'unique_together': {('name', 'province', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ProvinceI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'),
                                                     ('tr', 'Turkish'), ('kg', 'Kyrgyz')],
                                            max_length=2)),
                ('name', models.CharField(max_length=64, verbose_name='Translation')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='translations',
                                               to='locations.province',
                                               verbose_name='Original name')),
            ],
            options={
                'verbose_name': 'province translation',
                'db_table': 'province_i18n',
                'unique_together': {('province', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='CountryI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'),
                                                     ('tr', 'Turkish'), ('kg', 'Kyrgyz')],
                                            max_length=2)),
                ('name', models.CharField(max_length=64, verbose_name='Translation')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='translations',
                                              to='locations.country',
                                              verbose_name='Original name')),
            ],
            options={
                'verbose_name': 'country translation',
                'db_table': 'country_i18n',
                'unique_together': {('country', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='CityI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'),
                                                     ('tr', 'Turkish'), ('kg', 'Kyrgyz')],
                                            max_length=2)),
                ('name', models.CharField(max_length=64, verbose_name='Translation')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                           related_name='translations',
                                           to='locations.city',
                                           verbose_name='Original name')),
            ],
            options={
                'verbose_name': 'city translation',
                'db_table': 'city_i18n',
                'unique_together': {('city', 'locale')},
            },
        ),
    ]
