# Generated by Django 3.2 on 2022-01-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20220122_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Program level'},
        ),
    ]
