# Generated by Django 3.2 on 2021-12-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='cityi18n',
            options={'verbose_name': 'city translation'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='countryi18n',
            options={'verbose_name': 'country translation'},
        ),
        migrations.AlterModelOptions(
            name='provincei18n',
            options={'verbose_name': 'province translation'},
        ),
        migrations.AlterField(
            model_name='cityi18n',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='locations.city', verbose_name='Original name'),
        ),
        migrations.AlterField(
            model_name='cityi18n',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cityi18n',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Translation'),
        ),
        migrations.AlterField(
            model_name='countryi18n',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='locations.country', verbose_name='Original name'),
        ),
        migrations.AlterField(
            model_name='countryi18n',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2),
        ),
        migrations.AlterField(
            model_name='countryi18n',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Translation'),
        ),
        migrations.AlterField(
            model_name='provincei18n',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2),
        ),
        migrations.AlterField(
            model_name='provincei18n',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Translation'),
        ),
        migrations.AlterField(
            model_name='provincei18n',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='locations.province', verbose_name='Original name'),
        ),
    ]
