# Generated by Django 3.2 on 2021-12-15 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default='NON', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='no match', message='ISO code has to be of length 3', regex='^.{3}$')]),
        ),
    ]
