# Generated by Django 3.2 on 2021-12-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20211215_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['updated_at'], 'verbose_name_plural': 'countries'},
        ),
    ]
