# Generated by Django 3.2 on 2021-12-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
