# Generated by Django 3.2.5 on 2021-07-24 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_country_iso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='no match', message='ISO code has to be of length 3', regex='^.{3}$')]),
        ),
    ]
