# Generated by Django 3.2 on 2022-01-07 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DegreeI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overview', models.TextField(verbose_name='Description')),
                ('title', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Link to program details')),
                ('duration', models.IntegerField(default=0, verbose_name='Study duration in month(s)')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Application deadline')),
                ('degree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degree', to='programs.degree')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='institutions.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
            ],
            options={
                'unique_together': {('season', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TermI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2)),
                ('season', models.CharField(max_length=32)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='programs.term')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('kg', 'Kyrgyz')], max_length=2)),
                ('overview', models.TextField()),
                ('title', models.CharField(max_length=128)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='programs.program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='')),
                ('tuition', models.IntegerField(default=0)),
                ('housing', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('USD', 'US dollar')], default='USD', max_length=3)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fee', to='programs.program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
    ]
