# Generated by Django 3.2 on 2022-01-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_image'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='institution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='fee', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='fee', to='programs.program'),
        ),
    ]
