# Generated by Django 3.2 on 2022-01-18 10:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20220118_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
