# Generated by Django 3.2 on 2022-01-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20220122_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='programs', to='programs.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='programs', to='programs.degree'),
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
    ]
