# Generated by Django 3.2 on 2022-02-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20220122_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
