# Generated by Django 3.2 on 2022-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_alter_faculty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='icon',
            field=models.CharField(default='', max_length=64),
        ),
    ]
