# Generated by Django 3.2.5 on 2021-07-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_city_cityi18n'),
        ('institutions', '0002_institution_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'city')},
        ),
    ]
