name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Eduwise Backend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          password: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into

          script: |
            cd eduwise_backend/
            git pull origin main
#            python manage.py migrate
#            gunicorn eduwise.wsgi --bind 0.0.0.0:8000

